# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0002_auto_20170627_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 28, 12, 47, 27, 481043, tzinfo=utc), verbose_name='time'),
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_time',
            field=models.TimeField(default=datetime.datetime(2017, 6, 28, 12, 47, 27, 480041, tzinfo=utc), verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rec_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date recorded'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='rec_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date recorded'),
        ),
    ]
